### PR TITLE
Functional Docker image

### PR DESCRIPTION
**Pull request by av-lukas**
This allows non-Mac users to compile the documentation inside a Docker container.

Here's the rendered PDF:
[main.pdf](https://github.com/aion-dk/crypto-protocol-documentation/files/11487089/main.pdf)

### CODE REVIEW

**Review by av-emil — DISMISSED** [review]
This substantially changes the actual content of the tex files.

**Comment by av-lukas** [comment]
Indeed. I've agreed with @stefan-av that this would be the case since his VSCode plugin is doing some black magic, either with the content or the compiler flags, that allows the document to have references that contain spaces. However, since I can't figure out how to replicate the behavior in the timebox I set myself with, I've replaced all spaces with underscores on the Linux-specific compiler.

**Comment by stefan-av** [comment]
I noticed you generally renamed labels with `_` instead of ` `.
You renamed sections, appendixes and algorithms but NOT the figures.
There are figures with spaces in their names, like [this one](https://github.com/aion-dk/crypto-protocol-documentation/blob/490d465ee354a12b7a5c33cfc0e53bad82f01ae7/Chapters/3.1_Overview.tex#L206).
Do you want to rename those as well for consistency?

**Comment by av-lukas** [comment]
Figures have also been changed to the new standard.

**Review by stefan-av — APPROVED** [review]

**Pull request merged**
